---
- platform: ffmpeg
  name: living room cam
  input: !secret living_room_cam_cmd
  extra_arguments: -pred 1 -q:v 2

- platform: local_file
  name: Driveway snapshot
  file_path: /config/www/snapshots/driveway.jpg

- platform: local_file
  name: Garden snapshot
  file_path: /config/www/snapshots/garden.jpg

- platform: local_file
  name: Living room snapshot
  file_path: /config/www/snapshots/living_room.jpg

- platform: local_file
  name: Kitchen snapshot
  file_path: /config/www/snapshots/kitchen.jpg

- platform: local_file
  name: Bedroom snapshot
  file_path: /config/www/snapshots/bedroom.jpg

- platform: local_file
  name: Office snapshot
  file_path: /config/www/snapshots/office.jpg
