---
- platform: mqtt
  name: Bedroom curtains
  command_topic: "switchbot/sb_upstairs/curtain/bedroom_curtains/set"
  qos: 0
  retain: true
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "PAUSE"
  position_topic: "switchbot/sb_upstairs/curtain/bedroom_curtains/position"
  position_template: "{{ value_json.pos }}"
  set_position_topic: "switchbot/sb_upstairs/curtain/bedroom_curtains/set"
  set_position_template: "{{ position }}"

- platform: mqtt
  name: Office curtain
  command_topic: "switchbot/sb_upstairs/curtain/office_curtain/set"
  qos: 0
  retain: true
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "PAUSE"
  position_topic: "switchbot/sb_upstairs/curtain/office_curtain/position"
  position_template: "{{ value_json.pos }}"
  set_position_topic: "switchbot/sb_upstairs/curtain/office_curtain/set"
  set_position_template: "{{ position }}"

- platform: mqtt
  name: Living room curtains
  command_topic: "switchbot/sb_downstairs/curtain/living_room_curtains/set"
  qos: 0
  retain: true
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "PAUSE"
  position_topic: "switchbot/sb_downstairs/curtain/living_room_curtains/position"
  position_template: "{{ value_json.pos }}"
  set_position_topic: "switchbot/sb_downstairs/curtain/living_room_curtains/set"
  set_position_template: "{{ position }}"
