---
- name: wigeon
  platform: wake_on_lan
  mac: '2C:FD:A1:BE:32:53'
  host: 192.168.1.1
  turn_off:
    service: shell_command.sleep_wigeon

- name: serpentine
  platform: wake_on_lan
  mac: '6C:BF:B5:01:96:C0'
  host: 192.168.2.8
  turn_off:
    service: shell_command.sleep_serpentine

- platform: template
  switches:
    rouen:
      value_template: "{{ states('sensor.dryer_plug_power')|int > 5 }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.dryer_plug_status
      turn_off:
        service: shell_command.rouen_off
      icon_template: 'mdi:gamepad-square'

- platform: template
  switches:
    tv:
      value_template: "{{ is_state('media_player.tv', 'on') }}"
      turn_on:
        service: wake_on_lan.send_magic_packet
        data:
          mac: 64:95:6C:51:52:1F
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.tv

    google_tv:
      value_template: "{{ not is_state('media_player.google_tv', 'off') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.google_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.google_tv

- platform: template
  switches:
    office_diffuser:
      icon_template: 'mdi:tailwind'
      value_template: >
        {{
          is_state_attr('fan.office_diffuser_control', 'speed', 'low')
          or
          is_state_attr('fan.office_diffuser_control', 'speed', 'high')
        }}
      turn_on:
        service: fan.set_speed
        data:
          entity_id: fan.office_diffuser_control
          speed: 'high'
      turn_off:
        service: fan.set_speed
        data:
          entity_id: fan.office_diffuser_control
          speed: 'off'

    living_room_diffuser:
      icon_template: 'mdi:tailwind'
      value_template: >
        {{
          is_state_attr('fan.living_room_diffuser', 'speed', 'low')
          or
          is_state_attr('fan.living_room_diffuser', 'speed', 'high')
        }}
      turn_on:
        service: fan.set_speed
        data:
          entity_id: fan.living_room_diffuser
          speed: 'high'
      turn_off:
        service: fan.set_speed
        data:
          entity_id: fan.living_room_diffuser
          speed: 'off'

- platform: bhyve

- platform: mqtt
  name: bazarr deployment
  icon: mdi:kubernetes
  unique_id: bazarr_deployment
  state_topic: mqtt-kube/bazarr/power/state
  command_topic: mqtt-kube/bazarr/power/set
  retain: true

- platform: mqtt
  name: calibre-web deployment
  icon: mdi:kubernetes
  unique_id: calibre_web_deployment
  state_topic: mqtt-kube/calibre-web/power/state
  command_topic: mqtt-kube/calibre-web/power/set
  retain: true

- platform: mqtt
  name: flood deployment
  icon: mdi:kubernetes
  unique_id: flood_deployment
  state_topic: mqtt-kube/flood/power/state
  command_topic: mqtt-kube/flood/power/set
  retain: true

- platform: mqtt
  name: komga deployment
  icon: mdi:kubernetes
  unique_id: komga_deployment
  state_topic: mqtt-kube/komga/power/state
  command_topic: mqtt-kube/komga/power/set
  retain: true

- platform: mqtt
  name: mylar deployment
  icon: mdi:kubernetes
  unique_id: mylar_deployment
  state_topic: mqtt-kube/mylar/power/state
  command_topic: mqtt-kube/mylar/power/set
  retain: true

- platform: mqtt
  name: nzbget deployment
  icon: mdi:kubernetes
  unique_id: nzbget_deployment
  state_topic: mqtt-kube/nzbget/power/state
  command_topic: mqtt-kube/nzbget/power/set
  retain: true

- platform: mqtt
  name: plex deployment
  icon: mdi:kubernetes
  unique_id: plex_deployment
  state_topic: mqtt-kube/plex/power/state
  command_topic: mqtt-kube/plex/power/set
  retain: true

- platform: mqtt
  name: pyload deployment
  icon: mdi:kubernetes
  unique_id: pyload_deployment
  state_topic: mqtt-kube/pyload/power/state
  command_topic: mqtt-kube/pyload/power/set
  retain: true

- platform: mqtt
  name: radarr deployment
  icon: mdi:kubernetes
  unique_id: radarr_deployment
  state_topic: mqtt-kube/radarr/power/state
  command_topic: mqtt-kube/radarr/power/set
  retain: true

- platform: mqtt
  name: sonarr deployment
  icon: mdi:kubernetes
  unique_id: sonarr_deployment
  state_topic: mqtt-kube/sonarr/power/state
  command_topic: mqtt-kube/sonarr/power/set
  retain: true

- platform: mqtt
  name: transmission deployment
  icon: mdi:kubernetes
  unique_id: transmission_deployment
  state_topic: mqtt-kube/transmission/power/state
  command_topic: mqtt-kube/transmission/power/set
  retain: true

- platform: mqtt
  name: Jackett deployment
  icon: mdi:kubernetes
  unique_id: jackett_deployment
  state_topic: mqtt-kube/jackett/power/state
  command_topic: mqtt-kube/jackett/power/set
  retain: true

- platform: template
  switches:
    transmission_deployment_shell:
      icon_template: mdi:kubernetes
      value_template: "{{ states('switch.transmission_deployment') }}"
      turn_on:
        service: shell_command.transmission_scale_up
      turn_off:
        service: shell_command.transmission_scale_down
