---
- name: wigeon
  platform: wake_on_lan
  mac: '2C:FD:A1:BE:32:53'
  host: 192.168.1.1
  turn_off:
    service: shell_command.sleep_wigeon

- platform: template
  switches:
    tv:
      value_template: "{{ is_state('media_player.tv', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.tv

- platform: template
  switches:
    office_diffuser:
      icon_template: 'mdi:tailwind'
      value_template: >
        {{
          is_state_attr('fan.office_diffuser_control', 'speed', 'low')
          or
          is_state_attr('fan.office_diffuser_control', 'speed', 'high')
        }}
      turn_on:
        service: fan.set_speed
        data:
          entity_id: fan.office_diffuser_control
          speed: 'high'
      turn_off:
        service: fan.set_speed
        data:
          entity_id: fan.office_diffuser_control
          speed: 'off'

    living_room_diffuser:
      icon_template: 'mdi:tailwind'
      value_template: >
        {{
          is_state_attr('fan.living_room_diffuser', 'speed', 'low')
          or
          is_state_attr('fan.living_room_diffuser', 'speed', 'high')
        }}
      turn_on:
        service: fan.set_speed
        data:
          entity_id: fan.living_room_diffuser
          speed: 'high'
      turn_off:
        service: fan.set_speed
        data:
          entity_id: fan.living_room_diffuser
          speed: 'off'

- platform: bhyve
