---
- alias: Cycle office lights
  description: Cycle office lights when tradfri2 on is pressed
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.tradfri2_action
      to: 'on'

  action:
    - service: input_select.select_next
      entity_id: input_select.office_lights

- alias: Turn off office lights when tradfri2 off is pressed
  mode: single

  trigger:
    - platform: state
      entity_id: sensor.tradfri2_action
      to: 'off'

  action:
    - service: switch.turn_off
      entity_id: switch.office_light_switch

    - service: light.turn_off
      entity_id: light.not_bulb
