---
- platform: integration
  source: sensor.router_plug_power
  name: tv total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.lights_power
  name: lights total power
  unit_prefix: k
  round: 2
