---
- platform: integration
  source: sensor.tv_plug_power
  name: tv total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.dishwasher_plug_power
  name: dishwasher total power
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.lights_power
  name: lights total power
  unit_prefix: k
  round: 2
