---
- alias: Clear presence when not on wifi
  id: away_no_wifi
  mode: queued

  trigger:
    - platform: state
      entity_id: sensor.rook_wifi_connection
      from: Beetroot

    - platform: state
      entity_id: device_tracker.4c_f2_02_ab_58_f5
      from: home

  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.living_room_presence
        - input_boolean.kitchen_presence
        - input_boolean.office_presence
        - input_boolean.bedroom_presence
        - input_boolean.bathroom_presence
        - input_boolean.garden_presence
