---
- alias: fridge_turn_on
  description: Turn on fridge when leaving living room
  mode: restart
  
  trigger:
    - platform: state
      entity_id:
        - input_boolean.living_room_presence
      to: 'off'

    - platform: template
      value_template: "{{ is_state_attr('media_player.tv', 'sound_output', 'bt_soundbar') }}"

  action:
    - service: switch.turn_on
      entity_id:
        - switch.fridge
