---
title: Automations
path: automations
icon: 'mdi:robot'
cards:
  - type: markdown
    content: '# [All Automations](/config/automation/dashboard)'

  - type: calendar
    initial_view: dayGridMonth
    entities:
      - calendar.calendar

  - type: entities
    title: Sun
    entities:
      - entity: sensor.dawn_time
      - entity: sensor.sunrise_time
      - entity: sensor.sunset_time
      - entity: sensor.dusk_time
      - type: attribute
        entity: sun.sun
        attribute: elevation
        name: Sun elevation
        icon: mdi:weather-sunset-down

  - type: entities
    title: Presence
    show_header_toggle: false
    state_color: true
    entities:
      - entity: automation.tv_auto_pause
        name: Pause tv when leaving room
        icon: 'mdi:television'
        secondary_info: last-triggered
      - entity: automation.music_no_speaker_pause
        name: Pause music when in room without speakers
        icon: 'mdi:music'
        secondary_info: last-triggered

  - type: entities
    title: Notifications
    show_header_toggle: false
    state_color: true
    entities:
      - entity: automation.doorbell_notification
        icon: 'mdi:doorbell'
        secondary_info: last-triggered
      - entity: automation.send_reminder_to_drink_water
        icon: 'mdi:cup'
        secondary_info: last-triggered
      - entity: automation.reenable_water_notifications
        icon: 'mdi:cup'
        secondary_info: last-triggered
      - entity: automation.send_notification_when_washing_machine_finishes
        icon: 'mdi:washing-machine'
        secondary_info: last-triggered
      - entity: automation.send_notification_when_dryer_finishes
        icon: 'mdi:tumble-dryer'
        secondary_info: last-triggered

  - type: entities
    title: Seasonal
    show_header_toggle: false
    state_color: true
    entities:
      - entity: automation.turn_off_window_led_strips_later_at_night
        icon: 'mdi:led-strip-variant'
        secondary_info: last-triggered
      - entity: automation.turn_on_window_led_strips_at_sunset
        icon: 'mdi:led-strip-variant'
        secondary_info: last-triggered

  - type: entities
    title: Other
    show_header_toggle: false
    state_color: true
    entities:
      - entity: automation.turn_on_guest_mode_when_cleaner_arrives
        icon: 'mdi:account-multiple-plus'
        secondary_info: last-triggered
      - entity: automation.tv_wigeon_sleep
        name: Put wigeon to sleep when turning on the tv
        icon: 'mdi:television'
        secondary_info: last-triggered
