---
title: Automations
path: automations
icon: 'mdi:robot'
cards:
  - type: markdown
    content: '# [All Automations](/config/automation/dashboard)'

  - type: calendar
    initial_view: dayGridMonth
    entities:
      - calendar.calendar

  - type: entities
    title: Sun
    entities:
      - entity: sensor.dawn_time
      - entity: sensor.sunrise_time
      - entity: sensor.sunset_time
      - entity: sensor.dusk_time

  - type: entities
    title: Notifications
    show_header_toggle: false
    state_color: true
    entities:
      - entity: automation.doorbell_notification
        icon: 'mdi:doorbell'
        secondary_info: last-triggered

  - type: entities
    title: Other
    show_header_toggle: false
    state_color: true
    entities:
      - entity: automation.turn_on_guest_mode_when_cleaner_arrives
        icon: 'mdi:account-multiple-plus'
        secondary_info: last-triggered
