---
- alias: Doorbell notification
  id: 'doorbell_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_doorbell_pressed
      to: 'on'

  action:
    - service: notify.gotify_high
      data:
        title: Doorbell
        message: Someone pressed the doorbell

    - service: notify.lg_webos_smart_tv
      data:
        message: Someone pressed the doorbell

- alias: Doorbell motion detection notification
  id: 'doorbell_motion_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_person_detected
      to: 'on'

  action:
    - service: notify.gotify
      data:
        title: Doorbell
        message: Someone is at the door

    - service: notify.lg_webos_smart_tv
      data:
        message: Someone is at the door

- alias: Stream driveway when doorbell is pressed
  id: 'doorbell_camera_stream'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_doorbell_pressed
      to: 'on'

  condition:
    - condition: state
      entity_id: switch.tv
      state: 'on'

  action:
    - service: camera.play_stream
      target:
        entity_id: camera.driveway
      data:
        media_player: media_player.front_room_tv

- alias: Ring doorbell on home speakers
  id: 'doorbell_home_speakers'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_doorbell_pressed
      to: 'on'

  action:
    - service: media_player.volume_set
      target:
        entity_id:
          - media_player.bedroom_speaker
          - media_player.office_speaker
      data:
        volume_level: 0.5

    - repeat:
        count: 3
        sequence:
          - service: media_player.play_media
            target:
              entity_id:
                - media_player.bedroom_speaker
                - media_player.office_speaker
            data:
              media_content_id: https://github.com/johnzanussi/unifi-g4-doorbell-sounds/blob/main/sounds/sounds_ring_button/Ding-dong.wav?raw=true
              media_content_type: music

          - delay: 3
