---
- alias: Doorbell notification
  id: 'doorbell_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_doorbell_pressed
      to: 'on'

  action:
    - service: notify.gotify_high
      data:
        title: Doorbell
        message: Someone pressed the doorbell

    - service: notify.tv
      data:
        message: Someone pressed the doorbell

- alias: Doorbell motion detection notification
  id: 'doorbell_motion_notification'
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_person_detected
      to: 'on'

  action:
    - service: notify.gotify
      data:
        title: Doorbell
        message: Someone is at the door

    - service: notify.tv
      data:
        message: Someone is at the door

- alias: play camera on tv when doorbell is pressed
  id: tv_camera_doorbell_press
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_doorbell_pressed
      to: 'on'

  conditions:
    - platform: state
      entity_id: switch.tv
      state: 'on'

  action:
    - service: camera.play_stream
      target:
        entity_id: camera.driveway
      data:
        media_player: media_player.front_room_tv
