---
- alias: Open curtains at sunrise
  id: curtains_open_sunrise
  mode: single

  trigger:
    platform: sun
    event: sunrise

  action:
    # add random delays if possible to look more natural
    - service: cover.open_cover
      target:
        entity_id:
          - cover.office_curtain
          - cover.living_room_curtains

- alias: Close curtains at sunset
  id: curtains_close_sunset

  trigger:
    # platform: sun
    # event: sunset
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -3

  action:
    # add random delays if possible to look more natural
    - service: cover.close_cover
      target:
        entity_id:
          - cover.bedroom_curtains
          - cover.office_curtain
          - cover.living_room_curtains
