---
- alias: Turn on lights when sun sets
  id: sunset_lights_on
  mode: single

  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"

  action:
    - service: script.living_room_lights
    - service: script.kitchen_lights
    - service: script.bedroom_lights
    - service: script.office_lights

- alias: Turn off lights when sun rises
  id: sunset_lights_off
  mode: single

  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.living_room_light_switch
        - switch.kitchen_light_switch
        - switch.bedroom_light_switch
        - switch.office_light_switch

- alias: Turn on window led strips at sunset
  id: window_leds_sunset

  trigger:
    # platform: sun
    # event: sunset
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -1

  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.wled_living_room_window
          - light.wled_bedroom_window
      data:
        brightness_pct: 100
