---
- alias: Turn off window led strips later at night
  id: window_leds_off

  trigger:
    - platform: time
      at:
        - "22:00"

  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id:
          - light.wled_living_room_window
          - light.wled_bedroom_window
