---
- platform: powercalc
  create_group: WLED bedroom
  entities:
    - entity_id: light.wled_bed
      wled:
        voltage: 5
    - entity_id: light.wled_bedroom_dresser
      wled:
        voltage: 5

- platform: powercalc
  create_group: WLED windows
  entities:
    - entity_id: light.wled_living_room_window
      wled:
        voltage: 5
    - entity_id: light.wled_bedroom_window
      wled:
        voltage: 5

- platform: powercalc
  entity_id: light.wled_kitchen
  standby_power: 0.5
  wled:
    voltage: 5
