---
- platform: template
  sensors:
    lights_power:
      friendly_name: Lights power
      value_template: >-
        {{ 
          states('sensor.not_bulb_power')|default(0)|float +
          states('sensor.shelly_not_bulb_living_room_power')|default(0)|float +
          states('sensor.shelly_garden_power')|default(0)|float +

          states('sensor.wled_bed_power')|default(0)|float +
          states('sensor.wled_bedroom_dresser_power')|default(0)|float +
          states('sensor.wled_living_room_window_power')|default(0)|float +
          states('sensor.wled_bedroom_window_power')|default(0)|float +
          states('sensor.wled_kitchen_power')|default(0)|float +

          states('light.stairs_upstairs_bulb')|default(0)|float +
          states('light.stairs_downstairs_bulb')|default(0)|float +

          states('sensor.living_room_light_switch_power_2')|default(0)|float +
          states('sensor.bedroom_light_switch_power')|default(0)|float +
          states('sensor.office_light_switch_power')|default(0)|float +
          states('sensor.bathroom_light_switch_power')|default(0)|float
        }}
      icon_template: 'mdi:lightbulb-on-outline'
      unit_of_measurement: W
