---
- platform: template
  sensors:
    wigeon_polybar:
      friendly_name: Wigeon polybar
      value_template: >
         {{ state_attr('climate.office', 'temperature') }}°
         {{ state_attr('climate.office', 'current_temperature') }}°
        ﲋ {{ states('sensor.office_humidity') }}
        {% if (states('input_number.water_drinking_daily')|int) < (states('sensor.expected_water_drunk')|int) -%}
        戴
        {% else -%}
        懲
        {% endif -%}
        {{ (states('input_number.water_drinking_daily')|int)/1000 }}
         {{ states('sensor.wigeon_current_consumption') }}W
      icon_template: 'mdi:dots-horizontal'
