---
- platform: template
  sensors:
    all_power:
      friendly_name: All power
      value_template: >-
        {{
          states('sensor.wigeon_current_consumption')|default(0)|float +
          states('sensor.paddlepond_current_consumption')|default(0)|float +
          states('sensor.tv_plug_power')|default(0)|float +
          states('sensor.fridge_current_consumption')|default(0)|float +
          states('sensor.dishwasher_current_consumption')|default(0)|float +
          states('sensor.washing_machine_current_consumption')|default(0)|float +
          states('sensor.dryer_current_consumption')|default(0)|float +
          states('sensor.lights_power')|default(0)|float
        }}
      icon_template: mdi:flash
      unit_of_measurement: W

    all_power_total:
      friendly_name: All power total
      value_template: >-
        {% if is_number(states('sensor.wigeon_total_consumption')) and
              is_number(states('sensor.paddlepond_total_consumption')) and 
              is_number(states('sensor.tv_total_power')) and 
              is_number(states('sensor.fridge_total_consumption')) and 
              is_number(states('sensor.dishwasher_total_consumption')) and 
              is_number(states('sensor.washing_machine_total_consumption')) and 
              is_number(states('sensor.dryer_total_consumption')) and 
              is_number(states('sensor.lights_total_power')) %}
          {{
            states('sensor.wigeon_total_consumption')|float +
            states('sensor.paddlepond_total_consumption')|float +
            states('sensor.tv_total_power')|float +
            states('sensor.fridge_total_consumption')|float +
            states('sensor.dishwasher_total_consumption')|float +
            states('sensor.washing_machine_total_consumption')|float +
            states('sensor.dryer_total_consumption')|float +
            states('sensor.lights_total_power')|float
          }}
        {% else %}
          None
        {% endif %}
      icon_template: mdi:flash
      unit_of_measurement: kWh

    all_power_monthly_cost:
      friendly_name: All power monthly cost
      value_template: >-
        {{
          (
            (now().day * 0.3792) +
            (states('sensor.all_monthly_energy_2')|float * 0.2924)
          ) | round(2)
        }}
      icon_template: mdi:currency-gbp
      unit_of_measurement: £
